### ISSUE TITLE
Azure ArcBox Workbook missed [ITPro flavor]

### ISSUE THREAD

**Issue by KoprowskiT** [Azure/arc_jumpstart_docs#175]
Hi Team,

I recently (last evening, Nov 21st) implemented ITPro Azure ArcBox following detailed instructions from the newest version of the page  [Jumpstart ArcBox for IT Pros](https://arcjumpstart.com/azure_jumpstart_arcbox/ITPro). However, after fighting with some issues - problems with implementing MA/MMA agent on ArcBOX-SQL (it was necessary to reimplement agents manually, from within the virtual machine) most problems connected with MFA challenges - I landed with lack of Arc workbook.

Based on document and rg_arc [picture](docs/azure_jumpstart_arcbox/ITPro/rg_arc.png) there should be a workbook ready to use. Sadly in my implementation it is not exist:

Here is the standard list of all resources
![image](https://github.com/Azure/arc_jumpstart_docs/assets/4272123/3f77e75d-b55f-44c6-82f2-83c0d02785e3)

Here is the expanded list of all resources
![image](https://github.com/Azure/arc_jumpstart_docs/assets/4272123/19d55c9b-7309-43c0-a1fd-34de152e2ac3)

And there is no errors about workbook in this deployment (only one error is with double deployment of AMA.

Can we please investigate if this is only mine problem?

**Comment by sebassem** [comment]
@KoprowskiT Thank you for submitting this issue, we will investigate and get back to you

**Comment by sebassem** [comment]
@KoprowskiT Can you share the output of the MonitorWorkbookLogonScript log under C:\ArcBox ?

**Comment by KoprowskiT** [comment]
Yes, of course. 
1. log attached
It looks like an error saying, "AADSTS700016: Application with identifier 'JumpstartArcBoxSPN' was not found in the directory." However, that application exists in the directory.
[MonitorWorkbookLogonScript.txt](https://github.com/Azure/arc_jumpstart_docs/files/13461800/MonitorWorkbookLogonScript.txt)

2. print screen from the app attached
I've two under the same name (the first one is from the first implementation (failed), but the second is operational
![image](https://github.com/Azure/arc_jumpstart_docs/assets/4272123/e7f6a4de-192e-423e-8b92-27010b540dd6)

3.  print screen from SPN credential
I used data from SPN (credential) in the template during deployment
![image](https://github.com/Azure/arc_jumpstart_docs/assets/4272123/31f58d6b-7357-48c0-972e-1ff710c83f09)

I'm assuming - deployment will fail with the wrong (or lack of) SPN. 

4. Multiple times, scripts were requested: "_Please run 'az login' to set up account." and "_Failed to obtain access token_" as far I remember, enforcement of MFA, can bring this problem, and az login didn't work well all the time. A few times, I had to use az login with the device code.
Attached Arcservers logon script logs.
[ArcServersLogonScript.txt](https://github.com/Azure/arc_jumpstart_docs/files/13461874/ArcServersLogonScript.txt)

**Comment by sebassem** [comment]
@KoprowskiT  Thanks for sharing the logs and more context. The service principal needs to be able to login non-interactively so requiring MFA for the service principal won't work, you need to exclude it from this policy for the automation to complete.

**Comment by sebassem** [comment]
@KoprowskiT I just noticed that the [only actions for conditional access policies on service principals](https://learn.microsoft.com/entra/identity/conditional-access/workload-identity) are block or grant there is no MFA action.
