### ISSUE TITLE
Code snippet to create service principal for Microsoft Azure: Windows Server Virtual Machine has error, causing it to fail

### ISSUE THREAD

**Issue by GeldHades27355** [Azure/arc_jumpstart_docs#285]
Currently, the snippet is
`az login`
`subscriptionId=$(az account show --query id --output tsv)`
`az ad sp create-for-rbac -n "<Unique SP Name>" --role "Contributor" --scopes /subscriptions/$subscriptionId`

However, the $ declaring the variable subscriptionID slipped. It should be:

`az login`
`$subscriptionId=(az account show --query id --output tsv)`
`az ad sp create-for-rbac -n "<Unique SP Name>" --role "Contributor" --scopes /subscriptions/$subscriptionId`

**Comment by dkirby-ms** [comment]
Please share the page where you see this. Are you certain that the syntax is for PowerShell and not for Bash shell?

**Comment by GeldHades27355** [comment]
Here: https://azurearcjumpstart.io/azure_arc_jumpstart/azure_arc_servers/azure/azure_arm_template_win
![image](https://github.com/Azure/arc_jumpstart_docs/assets/143819181/7c9939dc-3450-4a1d-8a1c-7fffec145943)

It worked fine (after moving the $ to the right place) on PowerShell, so I assume the code is for PowerShell. 😉

**Comment by dkirby-ms** [comment]
Thanks. The doc is ambiguous and needs to be clarified more to avoid this confusion. The script is actually a shell script and not a PowerShell script, but you are right that adding the $ makes it work for PowerShell too. We will review the doc for clarity and update as required.

**Comment by GeldHades27355** [comment]
🤣 Sorry about that. I just automatically run stuff in powershell, since its the default "go to" console for most things Microsoft.

Thanks for pointing it out tho. 👍
________________________________
Von: Dale Kirby ***@***.***>
Gesendet: Montag, 22. April 2024 16:40
An: Azure/arc_jumpstart_docs ***@***.***>
Cc: Dom Côté ***@***.***>; Author ***@***.***>
Betreff: Re: [Azure/arc_jumpstart_docs] Code snippet to create service principal for Microsoft Azure: Windows Server Virtual Machine has error, causing it to fail (Issue #285)


Thanks. The doc is ambiguous and needs to be clarified more to avoid this confusion. The script is actually a shell script and not a PowerShell script, but you are right that adding the $ makes it work for PowerShell too. We will review the doc for clarity and update as required.
