### ISSUE TITLE
Failed to deploy Azure Arc-enabled servers connectivity behind a proxy server

### ISSUE THREAD

**Issue by basimolimajeed** [Azure/arc_jumpstart_docs#303]
When trying to use the proxy scenario the client fails to onboard, because it cannot connect to aka.ms. See attached

![image](https://github.com/Azure/arc_jumpstart_docs/assets/16608331/0b2fcb80-368d-4c3c-adb9-4201c4aadcac)

**Comment by lanicolas** [comment]
Hello @basimolimajeed thank you for your feedback this issue was addressed in a PR please try the latest version of the code it should be fixed
