### ISSUE TITLE
Provisioning of VM extension installscript_CAPI has timed out

### ISSUE THREAD

**Issue by StefDBA** [Azure/arc_jumpstart_docs#352]
Hello,

I try to install the DataOps flavor through Azure Portail, on Main Branch.

After 90 minutes, the installation failed with:
Provisioning of VM extension installscript_CAPI has timed out. Extension provisioning has taken too long to complete. The extension last reported "Plugin enabled".

More information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot (Code: VMExtensionProvisioningTimeout)
Troubleshooting Options

When I do the post deployment, I have errors around pods creation because of a missing CAPI file under \.kube\config-capi.

Capacity is fine, I use North Europe.

[Logs.zip](https://github.com/user-attachments/files/16512193/Logs.zip)

**Comment by StefDBA** [comment]
I do exactly the same deployment after deleting the RG created previously in DataOps to release quotas, and deployed again this time with full flavor, and it worked. Means I'm missing de DR configuration.

**Comment by janegilring** [comment]
Checkout [Introducing ArcBox 3.0 General Availability ](https://techcommunity.microsoft.com/t5/azure-arc-blog/introducing-arcbox-3-0-general-availability/ba-p/4217103)which contains information about our latest release of ArcBox.

Relevant for the use of the Full flavor:

> In this release, we decided to deprecate the good old “Full” flavor of ArcBox. To keep things consistent and easier to maintain, while keeping the core experience for every user profile, we invested in making multiple improvements and optimizations to the existing “ITPros”, “DevOps”, and “DateOps” ArcBox flavors.

In addition, CAPI has been replace by k3s in the new release.

Please try out the updated version and feel free to report any issues in the [azure_arc repository](https://github.com/microsoft/azure_arc).
