### ISSUE TITLE
Microsoft SQL Server Management Studio Desktop Link is broken

### ISSUE THREAD

**Issue by StefDBA** [Azure/arc_jumpstart_docs#353]
Hello,

In full flavor, the desktop link to  SSMS still refers version 19 when version 20 is installed
The target should be C:\Program Files (x86)\Microsoft SQL Server Management Studio 20\Common7\IDE\Ssms.exe when it is C:\Program Files (x86)\Microsoft SQL Server Management Studio **19**\Common7\IDE\Ssms.exe

**Comment by janegilring** [comment]
Checkout [Introducing ArcBox 3.0 General Availability ](https://techcommunity.microsoft.com/t5/azure-arc-blog/introducing-arcbox-3-0-general-availability/ba-p/4217103) which contains information about our latest release of ArcBox.

Relevant for the use of the Full flavor:

> In this release, we decided to deprecate the good old “Full” flavor of ArcBox. To keep things consistent and easier to maintain, while keeping the core experience for every user profile, we invested in making multiple improvements and optimizations to the existing “ITPros”, “DevOps”, and “DateOps” ArcBox flavors.

Please try out the updated version and feel free to report any issues in the [azure_arc repository](https://github.com/microsoft/azure_arc).
