### ISSUE TITLE
C:\ArcBox\SqlQueryStress.zip is missing

### ISSUE THREAD

**Issue by StefDBA** [Azure/arc_jumpstart_docs#354]
When SqlQueryStress is installed, the script reports a missing file C:\ArcBox\SqlQueryStress.zip. I downloaded SqlQueryStress.exe from Git and added it in C:\ArcBox\SqlQueryStress to have the desktop shortcut working.

**Comment by janegilring** [comment]
Checkout [Introducing ArcBox 3.0 General Availability ](https://techcommunity.microsoft.com/t5/azure-arc-blog/introducing-arcbox-3-0-general-availability/ba-p/4217103)which contains information about our latest release of ArcBox.

We have verified that the desktop shortcut for SqlQueryStress.exe works in the new version.
