### ISSUE TITLE
Issues deploying Jumpstart Agora

### ISSUE THREAD

**Issue by davidcan42** [Azure/arc_jumpstart_docs#398]
Hello,

I've been following the deployment Guideline for Jumpstart Agora found here:

https://azurearcjumpstart.com/azure_jumpstart_ag/manufacturing/contoso_motors/deployment

I'm pretty sure I've followed every step but haven't been able to deploy it successfully. I have encountered two errors:

1) In the documentation it says that you can deploy to the region of West Europe (my preferred location). However when attempting the deployment I get the following error saying that the particular VM used for this deployment isn't supported in western europe:

{"status":"Failed","error":{"code":"DeploymentFailed","target":"/subscriptions/8545877d-ff5b-435e-98ca-579eda867b17/resourceGroups/TestingAIO/providers/Microsoft.Resources/deployments/main","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see
https://aka.ms/arm-deployment-operations
for usage details.","details":[{"code":"InvalidTemplateDeployment","message":"The template deployment 'clientVmDeployment' is not valid according to the validation procedure. The tracking id is 'e9245e6b-8ad7-4062-af55-b02998883310'. See inner errors for details.","details":[{"code":"SkuNotAvailable","message":"The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_D32s_v5' is currently not available in location 'westeurope'. Please try another size or deploy to a different location or different zone. See
https://aka.ms/azureskunotavailable
for details."}]}]}}

2) I then attempted a different region. This time North Europe. It seemed to be working but then I received the following deployment error:

Error message: 'Command execution finished, but failed because it returned a non-zero exit code of: '1'. The command had an error output of: 'C:\\Packages\\Plugins\\Microsoft.Compute.CustomScriptExtension\\1.10.17\\Downloads\\1\\Bootstrap.ps1 : Missing an argument \r\nfor parameter 'customLocationRPOID'. Specify a parameter of type 'System.String' and try again.\r\n    + CategoryInfo          : InvalidArgu...' For more information, check the instance view by executing Get-AzVmssVm or Get-AzVm (https://aka.ms/GetAzVm). These commands can be executed using CloudShell ([https://aka.ms/CloudShell)'.](https://aka.ms/CloudShell)%27.) More information on troubleshooting is available at https://aka.ms/VMExtensionCSEWindowsTroubleshoot.
 
Which according to the guidance I thought that variable had been defined. However, after doing some more checks, I realized that the value of my RPOID is actually blank. This is what I got:
 
{
  "value": []
}
 
I followed the guidance step by step, is there something I'm missing that I should've done or had in my subscription/tenant and I don't have?

**Comment by sebassem** [comment]
@davidcan42 thanks for opening the issue. In the docs as you mentioned, there is one step to initialize this variable, can you double-check it is set and then confirm that you are passing it explicity in the Azure cli deployment command?

**Comment by davidcan42** [comment]
Hello @sebassem!

Thank you very much for getting back to me on this. With regards to your question, yes I had previously initialized and checked the variable and it was still  blank. After doing some research and digging it turns out that my SPN didn't have an actual RPOID! Apparently one of the reasons for this is that when your SPN is created if it's created without a Role then you don't get an RPOID. For some reason when mine was created the role wasn't assigned. So what seemed to solve it was first I did the following:
 
#Ensure the resource provider is registered
az provider register --namespace Microsoft.ExtendedLocation
 
Then I assigned the owner role, and after that I did get an RPOID. After that everything else worked smoothly and now it has all been deployed and I can try to do the next stage of the tutorial.

Given this part has been solved, I guess then what would be interesting to look at was why it didn't work in West Europe region when the docs say it does. For the deployment to work I had to deploy it in North Europe. 

Thanks for the help and please do let me know if there is anything I could do to help with the West Europe issue.

**Comment by sebassem** [comment]
@davidcan42 Great to hear you got past this issue. With regards to the westeurope problem, sometimes there are capacity constraints in some Azure datacenters which you are now facing with this specific VM SKU so usually its temporarily until more capacity is added. So the only thing to do now is to use another region unfortunately.
