### ISSUE TITLE
Generate-ARM-Template.ps1 not working on powershell version 5.1

### ISSUE THREAD

**Issue by BasBerk** [Azure/arc_jumpstart_docs#402]
Not that the Generate-ARM-Template.ps1 is mentioned in the topic "connect to HCIBox" is also not mentioning that is only works on Powershell version 7.x.
Meaning this script is failing with the out of the box config.

**Comment by janegilring** [comment]
@BasBerk Hi, could you provide some more information about the error message when not using PowerShell 7? Was it from powershell.exe or powershell_ise.exe?

As a side note, we are actively working on porting all automation scripts in HCIBox to run under PowerShell 7.

**Comment by BasBerk** [comment]
Sorry for the delay.
I followed the documentation on: https://azurearcjumpstart.com/azure_jumpstart_hcibox/cloud_deployment as much as possible.
_Now you will use the generated ARM template to validate the HCI cluster in Azure portal. Open File Explorer on HCIBox-Client and navigate to the C:\HCIBox folder. Right-click on the folder and open it in VSCode._

If my memory serves me right, tried starting it from Explorer and starting powershell.exe.
both resulting in the same error message. I see I forgot the mention the error message, I was a bit under pressure to delver the cluster on time. But I'm quite sure that you can reproduce the error.
Let me know if I can help with that.

**Comment by janegilring** [comment]
@BasBerk Thanks for the update. There are some [ongoing deployment issues](https://github.com/microsoft/azure_arc/issues?q=is%3Aissue+is%3Aopen+hcibox) with HCIBox currently being investigated. I suggest we wait until these are resolved before spending time on reproducing the error you encountered. If fine by you, let us close this issue for now - and you can re-open or create a new one if you can re-produce after the current issues are resolved.

**Comment by janegilring** [comment]
The deployment issues is now resolved, so you can fetch the latest updates from the GitHub repository and try a new deployment.
We also updated the automation to run under PowerShell 7 on the HCIBox Client VM.
