### ISSUE TITLE
Deployment failure if no email recipient given for autoshutdown

### ISSUE THREAD

**Issue by PetterTech** [Azure/arc_jumpstart_docs#404]
If you try to deploy ArcBox with the Auto Shutdown enabled AND do not input anything in the Auto Shutdown Email Recipient, the deployment of the shutdown-computevm-ArcBox-Client will fail causing the entire deployment to show as failed. 

The error message for the shutdown-computevm-ArcBox-Client deployment reads as follows: 
{"code":"MissingRequiredProperties","message":"One of the following properties must be specified: webhookUrl, emailRecipient."}

Reason I discovered this is that I would like the Arcbox client to autoshutdown at night, but I don't need an email when it does

**Comment by janegilring** [comment]
Thanks for reporting this issue @PetterTech.

It has been resolved in https://github.com/microsoft/azure_arc/pull/2701, this will be merged as soon as it has been reviewed.
