### ISSUE TITLE
Simulator not Transmitting Data in Edge IoT Ops Manufacturing Jumpstart

### ISSUE THREAD

**Issue by jblue6** [Azure/arc_jumpstart_docs#406]
I've set up the Azure IoT Ops Manufacturing Jumpstart (https://azurearcjumpstart.com/azure_arc_jumpstart/azure_edge_iot_ops/aio_manufacturing), using the Azure CLI to deploy via Bicep. 

The logon scripts have run successfully, but when I start the simulator, no data appears to be being transmitted.

![image](https://github.com/user-attachments/assets/5f481ce1-0ebd-484c-81cf-eb91cb548ce3)

The pod mqtt-simulator-deployment is in a CrashLoopBackOff state with error 

![image](https://github.com/user-attachments/assets/87ddf601-48bc-415b-9a77-21ac72fbdff4)

It maybe looks like its failing to discover the broker, but not 100% sure.

I've already resolved an issue with the aio-opc-asset-discovery service, by following the steps here https://learn.microsoft.com/en-us/azure/iot-operations/troubleshoot/known-issues#akri-services. All other pods seem to be up and in a Running state

I can't find any existing information on known issues here, but please let me know if there's something else I should try

**Comment by mrhoads** [comment]
Hi @jblue6.  Thanks for reporting this issue.  We're testing a fix for this with new images for the MQTT simulator and listener.  We'll follow-up as soon as possible once we confirm that this fixes the issue.

**Comment by sebassem** [comment]
This will be fixed once [this PR](https://github.com/microsoft/azure_arc/pull/2717) is merged

**Comment by fcabrera23** [comment]
Hi @jblue6,

This is already fixed. Please reopen if you face other issues.

Thanks,
Francisco
