### ISSUE TITLE
Update Screenshots to use newer branding for Agora

### ISSUE THREAD

**Issue by ldabas-msft** [Azure/arc_jumpstart_docs#408]
https://arcjumpstart.com/azure_jumpstart_ag/retail/contoso_supermarket

**Describe the issue or the bug**

Screenshots from old branding of jumpstart are being used in the contoso supermarket scenario.
The following image files need to be updated:
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ai/img/open_vscode.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ai/img/vscode_command_palette.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ai/img/vscode_dev_container_os.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ai/img/live_view_containers.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ai/img/live_view_containers_production.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ci_cd/img/open_vscode.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ci_cd/img/vscode_command_palette.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ci_cd/img/vscode_dev_container_os.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ci_cd/img/repo_staging_pods_gitops.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/ci_cd/img/repo_canary_pods_gitops.png
https://github.com/Azure/arc_jumpstart_docs/raw/main/docs/azure_jumpstart_ag/retail/contoso_supermarket/data_pos/img/locate_data_emulator_desktop.png

**Comment by likamrat** [comment]
Closed via #415
